language: cpp
dist: bionic

git:
  quiet: true

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

sudo: required

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - g++-7
            - libasio-dev
      env:
        - COMPILER=g++-7

    - os: linux
      addons:
        apt:
          packages:
            - g++-8
            - libasio-dev
      env:
        - COMPILER=g++-8

    - os: linux
      addons:
        apt:
          packages:
            - clang-5.0
            - libasio-dev
      env:
        - COMPILER=clang++-5.0

    - os: linux
      addons:
        apt:
          packages:
            - clang-6.0
            - libasio-dev
      env:
        - COMPILER=clang++-6.0

before_script:
  - export ROOT_FOLDER="$(pwd)"
  - export BUILD_FOLDER="$(pwd)/src"
  - cd ${BUILD_FOLDER}
  - export CXX=${COMPILER}
  - ${CXX} --version

script:
  # Check build without libosrm
  - make || travis_terminate 1
  # Check build with libosrm installed only if relevant files have
  # been modified.
  - CHANGED_FILES=`git diff --name-only master ${TRAVIS_COMMIT}`
  - echo ${CHANGED_FILES}
  - if echo ${CHANGED_FILES} | grep -v "libosrm_wrapper"; then travis_terminate 0; fi
  - make clean
  - cd ${ROOT_FOLDER}
  - sudo apt-get install build-essential git cmake pkg-config libbz2-dev libstxxl-dev libstxxl1v5 libxml2-dev libzip-dev libboost-all-dev lua5.2 liblua5.2-dev libtbb-dev libluabind-dev libluabind0.9.1v5
  - git clone https://github.com/Project-OSRM/osrm-backend.git
  - cd osrm-backend
  - git checkout v5.19.0
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build .
  - sudo cmake --build . --target install
  - cd ${BUILD_FOLDER}
  - make
